# Generated by Django 4.0.5 on 2022-06-21 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='제목')),
                ('thumbnail', models.ImageField(upload_to='', verbose_name='썸네일')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='설명')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('exposure_start', models.DateTimeField(verbose_name='노출 시작일')),
                ('exposure_end', models.DateTimeField(verbose_name='노출 종료일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
