# Generated by Django 4.0.5 on 2022-06-21 12:29

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_author_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exposure_end',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 28, 12, 29, 18, 269882, tzinfo=utc), verbose_name='노출 종료일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exposure_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='노출 시작일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='product/', verbose_name='썸네일'),
        ),
    ]
