# Generated by Django 4.0.5 on 2022-06-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='exposure_end',
            field=models.DateTimeField(null=True, verbose_name='노출 종료일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exposure_start',
            field=models.DateTimeField(null=True, verbose_name='노출 시작일'),
        ),
    ]
