# Generated by Django 4.0.5 on 2022-06-20 08:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='end_article',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 8, 48, 37, 756205, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='article',
            name='show_article',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 8, 48, 37, 755184, tzinfo=utc)),
        ),
    ]
