# Generated by Django 4.0.5 on 2022-06-20 08:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_end_article_alter_article_show_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_article',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 27, 8, 58, 32, 776812, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='show_article',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
