# Generated by Django 4.0.5 on 2022-06-22 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_end_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='end_article',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 7, 29, 40, 693694, tzinfo=utc)),
        ),
    ]
