# Generated by Django 4.0.5 on 2022-06-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_hobby_userprofile_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hobby',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to='user.hobby'),
        ),
    ]
