# Generated by Django 4.0.5 on 2022-06-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_userprofile_age_alter_userprofile_birthday_and_more_squashed_0007_alter_user_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(verbose_name='생일'),
        ),
    ]
